export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Login } from './Login/Login';
export { default as MyProfile } from './MyProfile/MyProfile';
export { default as Watchlist } from './Watchlist/Watchlist';
export { default as Movie } from './Movie/Movie';
export { default as Search } from './Search/Search';
export { default as RecommendedMovies } from './RecommendedMovies/RecommendedMovies';
export { default as RecommendedTvShows } from './RecommendedTvShows/RecommendedTvShows';
export { default as NotFountRoute } from './NotFountRoute/NotFountRoute';
